

export const TEST = "TEST";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORY = "SET_CATEGORY";
export const HANDLE_CARD_FIELD_CHANGE = "HANDLE_CARD_FIELD_CHANGE";
export const HANDLE_CATEGORY_FIELD_CHANGE = "HANDLE_CATEGORY_FIELD_CHANGE";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";